name: Build Changes

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build
        run: |
          mvn -q --projects auxiliar-connector --also-make install

      - name: FTP
        run: |
          echo ${{ secrets.FTP_USERNAME }}
          ls ./auxiliar-connector/target/*.jar