name: Upload File

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build
        run: |
          mvn -q clean
          mvn -q --projects auxiliar-connector,support-connector --also-make install

      - name: Retrieve Filename and Path
        id: ftp_files
        run: |
          modules="auxiliar-connector,support-connector"
          IFS=',' read -ra modules_array <<< "$modules"
          echo "First output array: ${modules_array[@]}"
          fileNames=()
          filesPath=()
          for name in "${modules_array[@]}"
          do
            fileNames+=($(ls -1 ./$name/target/*.jar | xargs basename))
            filesPath+=($(ls -1 ./$name/target/*.jar))
          done
          
          echo "Filenames array output1: ${fileNames[0]}"
          echo "Filenames array output2: ${fileNames[1]}"
          echo "Path array output: ${filesPath[@]}"
          
          echo ::set-output name=jarName::"${modules_array[@]}"
          echo ::set-output name=jarPath::"${filesPath[@]}"
        

      - name: Create a folder with jar files
        id: createFolders
        run: |
          connectorName=common
          tag=10.65.0.1
          
          echo "Jar names: ${{ steps.ftp_files.outputs.jarName }}"
          echo "Jar paths: ${{ steps.ftp_files.outputs.jarPath }}"
          
          jarPaths="${{ steps.ftp_files.outputs.jarPath }}"          
          jarNames="${{ steps.ftp_files.outputs.jarName }}"
          IFS=' ' read -ra jarNamesArray <<< "$jarNames"
          
          firstConnector="${jarNamesArray[0]}"
          releaseFolder=$tag"-"$connectorName
          
          echo "Release Folder: $releaseFolder"
          echo "First Connector Name: $firstConnector"
          echo "Connector Name: $connectorName"
          
          mkdir -p ./$firstConnector/target/filesToUpload/$releaseFolder
          
          for path in "${jarPaths[@]}"
          do
            mv -f $path ./$firstConnector/target/filesToUpload/$releaseFolder
          done
          
          ls -l ./$firstConnector/target/filesToUpload/
          
          echo "targetFolder=$firstConnector" >> $GITHUB_OUTPUT

      - name: Upload files to ftp server
        uses: wangyucode/sftp-upload-action@v2.0.2
        id: upload-to-ftp
        with:
          host: reposit.jitterbit.com
          username: gabriel.goncalves
          password: Netgear01@#!$
          localDir: './${{ steps.createFolders.outputs.targetFolder }}/target/filesToUpload'
          remoteDir: './Builds/connectors/CDATA/test/uploadedFile'
