name: Upload File

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build
        run: |
          mvn -q clean
          mvn -q --projects auxiliar-connector,support-connector --also-make install

      - name: FTP
        id: ftp_files
        run: |
          file=$(ls -1 ./auxiliar-connector/target/*.jar | xargs basename)
          path=$(ls -1 ./auxiliar-connector/target/*.jar)
          echo "Path: $path"
          echo "Filename: $file"
          echo "files=$file" >> $GITHUB_OUTPUT

      - name: Upload files to ftp server
        uses: wangyucode/sftp-upload-action@v2.0.2
        id: upload-to-ftp
        with:
          host: reposit.jitterbit.com
          username: gabriel.goncalves
          password: Netgear01@#!$
          local_path: ./auxiliar-connector/target/${{ steps.ftp_files.outputs.files }}
          remote_path: /gabriel.goncalves
