name: Upload File

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build
        run: |
          mvn -q clean
          mvn -q --projects auxiliar-connector,support-connector --also-make install

      - name: FTP
        id: ftp_files
        run: |
          modules="auxiliar-connector,support-connector"
          IFS=',' read -ra modules_array <<< "$modules"
          fileNames=()
          filesPath=()
          for name in "${modules[@]}"
          do
            fileNames=$(ls -1 ./name/target/*.jar | xargs basename)
            filesPath=$(ls -1 ./name/target/*.jar)
          done
          
          echo "${fileNames[@]}"
          echo "${filesPath[@]}"
          
          echo "jarName:$fileNames" >> $GITHUB_OUTPUT
          echo "jarPath:filesPath"  >> $GITHUB_OUTPUT
          
          echo "$jarName"
          echo "$jarPath"

      - name: Create a folder with jar files
        run: |
          ls ./auxiliar-connector
          mkdir -p ./auxiliar-connector/target/releaseTest
          mv -f ${{steps.ftp_files.outputs.full_path}} ./auxiliar-connector/target/releaseTest/
          ls -l ./auxiliar-connector/target/releaseTest/

      - name: Upload files to ftp server
        uses: wangyucode/sftp-upload-action@v2.0.2
        id: upload-to-ftp
        with:
          host: reposit.jitterbit.com
          username: gabriel.goncalves
          password: Netgear01@#!$
          localDir: './auxiliar-connector/target/releaseTest'
          remoteDir: './Builds/connectors/CDATA/test/uploadedFile'
