name: Build Changes

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Build
        run: |
          mvn -q clean
          mvn -q --projects auxiliar-connector,support-connector --also-make install

      - name: FTP
        id: ftp_files
        run: |
          names=auxiliar-connector
          echo "files=$names" >> $GITHUB_OUTPUT

      - name: Upload JAR files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /gabriel.goncalves/
          local-dir: ${{ steps.ftp_files.outputs.files }}/target/*.jar/