name: Req Flow

on: [ push ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up the Java environment
      - name: Preparing Environment
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Send request to Connector Repo
        run: |
          echo "Sending POST request for item TestAuto-Conn01"
          curl -X POST "https://connectorrepo.jitterbit.us/Api/Edit?handler=ReleaseVersionByConnectorName&ConnectorName=TestAuto-Conn01&releaseVersion=10.45.0.31" > stdout
          response=$(cat stdout)
          echo "Response: ${response}"
#          for item in "${{ matrix.items }}"; do
#            echo "Sending POST request for item ${item}"
#            curl -X POST "https://example.com/api/item/${item}" -H "Content-Type: application/json"
#          done