name: Auto Tag

on: [push]

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 99

      - name: Get latest release tag
        id: get_latest_release
        run: |
          git fetch --tags 
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "last tag: $latest_tag"
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Increment tag
        id: increment_tag
        run: |
          VERSION_BITS=(${{ steps.get_latest_release.outputs.latest_release }}//./)
          VNUM1=${VERSION_BITS[0]}
          VNUM2=${VERSION_BITS[1]}
          VNUM3=${VERSION_BITS[2]}
          VNUM4=${VERSION_BITS[3]}
          VNUM4=$((VNUM4+1))
          NEW_TAG="$VNUM1.$VNUM2.$VNUM3.$VNUM4"
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          echo "New created tag: $NEW_TAG"

      - name: Tag commit with new tag
        run: |
          echo "Tagging with ${{ steps.increment_tag.outputs.new_tag }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.increment_tag.outputs.new_tag }}
          git push origin ${{ steps.increment_tag.outputs.new_tag }}
